### PR TITLE
Make Static Methods

### PR DESCRIPTION
**Pull request by BrendanBenshoof**
This is a lot of changes all at once, and I really want a CR.

This ONLY converts all the commands to static methods. We still need to go back and document them all (I want help on that)

### CODE REVIEW

**Comment by amstocker** [comment]
Thanks, this is great and will solve #5.  Im wondering though, should we just turn command, argcommand, and filecommand into functions at this point?

**Comment by BrendanBenshoof** [comment]
Apathy is kicking in (that was a lot of difficult to automate typing :P ). As long as it works and adds minimal overhead, I am not too concerned by it.

Future modification and maintenance is unlikely to touch that bit of code very often.

**Comment by amstocker** [comment]
Yeah it is a lot to type, I don't blame you haha.  Looks good to me.

**Comment by amstocker** [comment]
Now we can hack away at copy http://ipfs.io/docs/commands/ into docstrings #5

**Comment by jbenet** [comment]
I'm curious why this is changing? tbh, the previous structure seems more maintainable to me. can probably use a metaclass if you're really worried about duplicating ptrs (i prob wouldn't be)

**Comment by jbenet** [comment]
(anyway i dont really care, whatever works for you guys :) :+1: )

**Comment by amstocker** [comment]
The [issue](#5) was that calling ``help()`` on api methods didnt provide any helpful documentation.  There probably is a fancier way to do it but this is fine imo

**Pull request merged**
