### PR TITLE
Add Python 3.x support

### PR DESCRIPTION
**Pull request by moreati**
- Uses six (and add it to install_requires) to cover moved/renamed modules

Fixes ipfs/python-ipfs-api#9

I also have doctests for ipfsApi.utils, those will be a separate PR

### CODE REVIEW

**Comment by amstocker** [comment]
Thanks so much!  There were some conflicts so I had to manually merge.

**Comment by moreati** [comment]
OK. Next time I'd be happy to rebase my branch, and preserve the commit messages that explained the changes

**Comment by amstocker** [comment]
Sorry!  Is there any way I can fix that?  I am not too experienced with managing git projects and I didn't know you could do that.

**Comment by moreati** [comment]
No problem, I'm still making git howlers from time to time. It's public now, so leave it be.

There are ways to fix it (e.g. rebase to remove the commits from the history, then force push), but they're messy and risk causing data loss. They shouldn't be applied to a public repo that other people are using - *particularly* the *master* branch of a repository that's being tracked by multiple forks tracking it.

**Comment by amstocker** [comment]
Ok you're probably right.  I'm just bummed you didn't get credit for the commits.

**Pull request closed without merging**
